"""init users, beam_marks and likes tables

Revision ID: b72e51a91241
Revises: 
Create Date: 2026-09-21 22:07:14.747437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b72e51a91241'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_username', sa.String(length=50), nullable=False),
    sa.Column('user_email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email'),
    sa.UniqueConstraint('user_username')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('beam_marks',
    sa.Column('beam_mark_id', sa.Integer(), nullable=False),
    sa.Column('beam_mark_name', sa.String(length=100), nullable=False),
    sa.Column('beam_mark_description', sa.String(length=1000), nullable=False),
    sa.Column('beam_mark_status', sa.String(length=20), nullable=False),
    sa.Column('beam_mark_image_url', sa.String(length=500), nullable=True),
    sa.Column('beam_mark_video_url', sa.String(length=500), nullable=True),
    sa.Column('beam_mark_price', sa.Float(), nullable=True),
    sa.Column('beam_mark_strength', sa.Float(), nullable=True),
    sa.Column('beam_mark_created_at', sa.DateTime(), nullable=True),
    sa.Column('beam_mark_published_at', sa.DateTime(), nullable=True),
    sa.Column('beam_mark_creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['beam_mark_creator_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('beam_mark_id')
    )
    op.create_index(op.f('ix_beam_marks_beam_mark_id'), 'beam_marks', ['beam_mark_id'], unique=False)
    op.create_table('likes',
    sa.Column('like_id', sa.Integer(), nullable=False),
    sa.Column('like_user_id', sa.Integer(), nullable=False),
    sa.Column('like_beam_mark_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['like_beam_mark_id'], ['beam_marks.beam_mark_id'], ),
    sa.ForeignKeyConstraint(['like_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('like_id')
    )
    op.create_index(op.f('ix_likes_like_id'), 'likes', ['like_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_likes_like_id'), table_name='likes')
    op.drop_table('likes')
    op.drop_index(op.f('ix_beam_marks_beam_mark_id'), table_name='beam_marks')
    op.drop_table('beam_marks')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
